# 03 · Results Extraction (R)

Converts network estimation outputs from `02_ggm_estimation` into analysis-ready
tables and KG-ready metadata tables for downstream knowledge-graph encoding.

## Inputs  (`../results/networks/`)

| File | Source |
|------|--------|
| `networks_summary.csv` | Written by Cell 5 of `02_ggm_estimation` |
| `edges_wave{W}_trust{S}_n{N}_{spec}.csv` | Edge lists per context × spec |
| `adj_wave{W}_trust{S}_n{N}_{spec}.csv` | Adjacency matrices per context × spec |
| `boot_edges_wave{W}_trust{S}_n{N}_{spec}.rds` | Bootstrap objects (g05 + g075 only) |

## Specifications

| Label | γ | Thresholded | In BKG |
|-------|---|-------------|--------|
| `g05`     | 0.50 | No  | Yes |
| `g075`    | 0.75 | No  | Yes |
| `g05_thr` | 0.50 | Yes | No  |

All three specs appear in analysis tables.  Only `g05` and `g075` are encoded in
the BKG (12 instances = 3 waves × 2 strata × 2 specs).

## Outputs  (`../results/networks/`)

**Analysis tables (all specs)**
- `edges_all.csv` — all nonzero undirected edges with context/spec metadata
- `bridge_edges.csv` — belief/affect ↔ behavior edges
- `node_metrics.csv` — degree and strength per node per context/spec
- `context_summary.csv` — context-level edge counts and behavior connectivity
- `edge_differences_high_minus_low.csv` — edge-wise (high − low) differences per wave/spec
- `bridge_differences_high_minus_low.csv` — bridge subset of the above
- `focal_belief_bridges.csv` — SEVERITY ↔ behavior edges
- `top_edges_top10.csv` — top-10 |weight| edges per network instance
- `edge_bootstrap_metrics.csv` — bootstrap CI/stability (g05 + g075 only)
- `edge_metrics.csv` — point estimates merged with bootstrap summaries

**KG-ready metadata tables (g05 + g075 only)**
- `kg_contexts.csv`
- `kg_gamma_specs.csv`
- `kg_network_instances.csv`

In [1]:
# ── Packages ──────────────────────────────────────────────────────────────────
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(stringr)
  library(tidyr)
  library(purrr)
  library(bootnet)   # needed in Cell 13 for readRDS of bootnet objects
})

NETWORK_DIR <- file.path("..", "results", "networks")

In [2]:
# ── Node metadata — defined as constants, NOT inferred from files ─────────────
# NODE_VARS order must match the estimation notebook exactly.
# Defining it here as a constant (rather than reading from the first adj file)
# makes this notebook independent of which file happens to be listed first.
NODE_VARS <- c(
  "SEVERITY",
  "AFF_FEAR", "AFF_WORRY", "WORRY_HEALTH_SYSTEM",
  "USE2_MASK", "USE2_SPACE150", "USE2_HANDWASH20", "USE2_AVOID"
)

NODE_DOMAIN <- c(
  SEVERITY            = "belief",
  AFF_FEAR            = "affect",
  AFF_WORRY           = "affect",
  WORRY_HEALTH_SYSTEM = "affect",
  USE2_MASK           = "behavior",
  USE2_SPACE150       = "behavior",
  USE2_HANDWASH20     = "behavior",
  USE2_AVOID          = "behavior"
)

FOCAL_NODE <- "SEVERITY"
PSY_NODES  <- names(NODE_DOMAIN)[NODE_DOMAIN %in% c("belief", "affect")]
BEH_NODES  <- names(NODE_DOMAIN)[NODE_DOMAIN == "behavior"]

# NODE_ROLE distinguishes the focal belief from all other nodes.
# Domain membership (belief / affect / behavior) is captured by NODE_DOMAIN.
NODE_ROLE <- setNames(
  ifelse(names(NODE_DOMAIN) == FOCAL_NODE, "focal_belief", "non_focal"),
  names(NODE_DOMAIN)
)

# ── Specification lookup ────────────────────────────────────────────────────────
# in_kg: whether the spec is stored as a BKG NetworkInstance.
# Only the main specification (g05, Pearson) is stored in the BKG.
# All others are robustness checks reported in the Results chapter only.
GAMMA_LOOKUP <- tibble(
  spec        = c("g05",      "g075",      "g05_thr",      "g05_spearman"),
  spec_id     = c("gamma_05", "gamma_075", "gamma_05_thr", "gamma_05_spearman"),
  gamma_ebic  = c(0.5,         0.75,        0.5,            0.5),
  thresholded = c(FALSE,       FALSE,       TRUE,           FALSE),
  cor_method  = c("pearson",   "pearson",   "pearson",      "spearman"),
  in_kg       = c(TRUE,        FALSE,       FALSE,          FALSE)
)

KG_SPECS <- filter(GAMMA_LOOKUP, in_kg)

TRUST_VARIABLE          <- "TRUST_RKI"
TRUST_GROUPING_RULE     <- "within-wave terciles"
MIDDLE_TERCILE_EXCLUDED <- TRUE

cat("NODE_VARS  :", paste(NODE_VARS,  collapse = ", "), "\n")
cat("KG specs   :", paste(KG_SPECS$spec, collapse = ", "), "\n")

NODE_VARS  : SEVERITY, AFF_FEAR, AFF_WORRY, WORRY_HEALTH_SYSTEM, USE2_MASK, USE2_SPACE150, USE2_HANDWASH20, USE2_AVOID
KG specs   : g05

In [3]:
# ── Load networks_summary.csv and discover files ──────────────────────────────
# networks_summary.csv is the authoritative record of what was estimated.
# File discovery is then cross-validated against it.

SUMMARY_PATH <- file.path(NETWORK_DIR, "networks_summary.csv")
if (!file.exists(SUMMARY_PATH))
  stop("networks_summary.csv not found. Run 02_ggm_estimation first.")

net_summary <- read_csv(SUMMARY_PATH, show_col_types = FALSE)
required_summary_cols <- c("wave","trust_stratum","n_cc","spec","gamma_ebic","threshold_applied")
missing_summary_cols  <- setdiff(required_summary_cols, names(net_summary))
if (length(missing_summary_cols) > 0)
  stop("networks_summary.csv missing columns: ", paste(missing_summary_cols, collapse=", "))

cat("networks_summary.csv: ", nrow(net_summary), " rows\n")

# ── Regex patterns: g05_thr ordered before g05 to prevent partial match ────────
SPEC_PATTERN <- paste(
  GAMMA_LOOKUP$spec[order(-nchar(GAMMA_LOOKUP$spec))],
  collapse = "|"
)

parse_meta <- function(path) {
  fname   <- basename(path)
  pattern <- paste0(
    "^(edges|adj|boot_edges)_wave(\\d+)_trust(low|high)_n(\\d+)_(",
    SPEC_PATTERN, ")\\.(csv|rds)$"
  )
  m <- str_match(fname, pattern)
  if (any(is.na(m))) return(NULL)
  tibble(
    kind          = m[2],
    wave          = as.integer(m[3]),
    trust_stratum = m[4],
    n_cc          = as.integer(m[5]),
    spec          = m[6],
    fname         = fname,
    path          = path
  )
}

edge_files <- list.files(NETWORK_DIR, pattern = "\\.csv$", full.names = TRUE)
edge_files <- edge_files[grepl("^edges_wave", basename(edge_files))]
adj_files  <- list.files(NETWORK_DIR, pattern = "\\.csv$", full.names = TRUE)
adj_files  <- adj_files[grepl("^adj_wave",   basename(adj_files))]
boot_files <- list.files(NETWORK_DIR, pattern = "\\.rds$", full.names = TRUE)
boot_files <- boot_files[grepl("^boot_edges_wave", basename(boot_files))]

edge_meta <- map_dfr(edge_files, parse_meta)
adj_meta  <- map_dfr(adj_files,  parse_meta)
boot_meta <- if (length(boot_files) > 0) map_dfr(boot_files, parse_meta) else tibble()

if (nrow(edge_meta) == 0) stop("No edge CSVs found in ", NETWORK_DIR)
if (nrow(adj_meta)  == 0) stop("No adjacency CSVs found in ", NETWORK_DIR)

stopifnot(all(edge_meta$spec %in% GAMMA_LOOKUP$spec))
stopifnot(all(adj_meta$spec  %in% GAMMA_LOOKUP$spec))
if (nrow(boot_meta) > 0)
  stopifnot(all(boot_meta$spec %in% GAMMA_LOOKUP$spec))

# ── Cross-validate file-parsed metadata against networks_summary.csv ───────────
# Every (wave, trust_stratum, n_cc, spec) row in the edge metadata should
# appear in networks_summary.csv; a mismatch indicates a stale file or
# a pipeline inconsistency.
edge_keys <- edge_meta %>% distinct(wave, trust_stratum, n_cc, spec)
summary_keys <- net_summary %>% distinct(wave, trust_stratum, n_cc, spec)
orphan_edges <- anti_join(edge_keys, summary_keys,
                          by = c("wave","trust_stratum","n_cc","spec"))
if (nrow(orphan_edges) > 0) {
  warning("Edge files found with no matching row in networks_summary.csv:\n",
          paste(capture.output(print(orphan_edges)), collapse="\n"))
}

# ── Verify adjacency files cover the same set as edge files ───────────────────
adj_keys  <- adj_meta  %>% distinct(wave, trust_stratum, n_cc, spec)
edge_no_adj <- anti_join(edge_keys, adj_keys, by = c("wave","trust_stratum","n_cc","spec"))
adj_no_edge <- anti_join(adj_keys, edge_keys, by = c("wave","trust_stratum","n_cc","spec"))
if (nrow(edge_no_adj) > 0) warning("Edge files without matching adj: ", nrow(edge_no_adj))
if (nrow(adj_no_edge) > 0) warning("Adj files without matching edge: ", nrow(adj_no_edge))

# ── Verify node order in adjacency files matches NODE_VARS ────────────────────
# Check first file; failures here indicate a node-ordering mismatch between
# the estimation and extraction notebooks.
W0m <- as.matrix(read.csv(adj_meta$path[1], row.names = 1, check.names = FALSE))
if (!identical(rownames(W0m), NODE_VARS))
  stop(
    "Node order in adjacency file does not match NODE_VARS constant.\n",
    "  File nodes : ", paste(rownames(W0m),   collapse=", "), "\n",
    "  NODE_VARS  : ", paste(NODE_VARS,        collapse=", ")
  )

cat("Found edge files    :", nrow(edge_meta), "\n")
cat("Found adj files     :", nrow(adj_meta),  "\n")
cat("Found bootstrap RDS :", nrow(boot_meta), "\n")
cat("  (bootstrap present for g05 and g075; g05_thr has no bootstrap by design)\n")
cat("Node order verified :", paste(NODE_VARS, collapse=", "), "\n")

networks_summary.csv:  24  rows
Found edge files    : 24
Found adj files     : 24
Found bootstrap RDS : 12
  (bootstrap present for g05 and g075; g05_thr has no bootstrap by design)
Node order verified : SEVERITY, AFF_FEAR, AFF_WORRY, WORRY_HEALTH_SYSTEM, USE2_MASK, USE2_SPACE150, USE2_HANDWASH20, USE2_AVOID

In [4]:
# ── Load all nonzero edges into one tidy table ────────────────────────────────
# edge_a / edge_b: canonical ordering (pmin / pmax) so every undirected edge
# has a single consistent representation regardless of which direction the
# adjacency matrix stored it.
# edge_id format: {network_id}__{edge_a}__{edge_b}
# The double-underscore separator works because NODE_VARS names contain
# no underscores that could create ambiguity.

edges_all <- edge_meta %>%
  mutate(dat = map(path, ~ read_csv(.x, show_col_types = FALSE))) %>%
  select(wave, trust_stratum, n_cc, spec, dat) %>%
  unnest(dat) %>%
  filter(weight != 0) %>%
  left_join(GAMMA_LOOKUP, by = "spec") %>%
  mutate(
    context_id  = paste0("ctx_w",  wave, "_", trust_stratum),
    network_id  = paste0("net_", spec, "_w", wave, "_", trust_stratum),
    edge_a      = pmin(from, to),
    edge_b      = pmax(from, to),
    edge_id     = paste(network_id, edge_a, edge_b, sep = "__"),
    abs_weight  = abs(weight),
    from_domain = NODE_DOMAIN[from],
    to_domain   = NODE_DOMAIN[to],
    from_role   = NODE_ROLE[from],
    to_role     = NODE_ROLE[to]
  ) %>%
  arrange(spec, wave, trust_stratum, desc(abs_weight))

# Sanity: no duplicate edge_ids within a network
dup_ids <- edges_all %>%
  group_by(edge_id) %>%
  filter(n() > 1) %>%
  nrow()
if (dup_ids > 0)
  stop(dup_ids, " duplicate edge_id values detected. Check adjacency export.")

write_csv(edges_all, file.path(NETWORK_DIR, "edges_all.csv"))
cat("Saved: edges_all.csv —", nrow(edges_all), "rows\n")
head(edges_all, 10)

Saved: edges_all.csv — 442 rows

   wave trust_stratum n_cc spec from            to                  weight
1  55   high          309  g05  AFF_FEAR        AFF_WORRY           0.5773954
2  55   high          309  g05  USE2_AVOID      USE2_SPACE150       0.2379412
3  55   high          309  g05  USE2_MASK       USE2_SPACE150       0.2135914
4  55   high          309  g05  USE2_HANDWASH20 USE2_SPACE150       0.2033636
5  55   high          309  g05  AFF_FEAR        SEVERITY            0.1963276
6  55   high          309  g05  USE2_HANDWASH20 USE2_MASK           0.1832615
7  55   high          309  g05  AFF_FEAR        WORRY_HEALTH_SYSTEM 0.1779615
8  55   high          309  g05  USE2_AVOID      USE2_HANDWASH20     0.1445860
9  55   high          309  g05  SEVERITY        USE2_AVOID          0.1407643
10 55   high          309  g05  SEVERITY        USE2_SPACE150       0.1274139
   spec_id  gamma_ebic thresholded ⋯ context_id   network_id
1  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
2  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
3  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
4  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
5  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
6  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
7  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
8  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
9  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
10 gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
   edge_a          edge_b
1  AFF_FEAR        AFF_WORRY
2  USE2_AVOID      USE2_SPACE150
3  USE2_MASK       USE2_SPACE150
4  USE2_HANDWASH20 USE2_SPACE150
5  AFF_FEAR        SEVERITY
6  USE2_HANDWASH20 USE2_MASK
7  AFF_FEAR        WORRY_HEALTH_SYSTEM
8  USE2_AVOID      USE2_HANDWASH20
9  SEVERITY        USE2_AVOID
10 SEVERITY        USE2_SPACE150
   edge_id                                          abs_weight from_domain
1  net_g05_w55_high__AFF_FEAR__AFF_WORRY            0.5773954  affect
2  net_g05_w55_high__USE2_AVOID__USE2_SPACE150      0.2379412  behavior
3  net_g05_w55_high__USE2_MASK__USE2_SPACE150       0.2135914  behavior
4  net_g05_w55_high__USE2_HANDWASH20__USE2_SPACE150 0.2033636  behavior
5  net_g05_w55_high__AFF_FEAR__SEVERITY             0.1963276  affect
6  net_g05_w55_high__USE2_HANDWASH20__USE2_MASK     0.1832615  behavior
7  net_g05_w55_high__AFF_FEAR__WORRY_HEALTH_SYSTEM  0.1779615  affect
8  net_g05_w55_high__USE2_AVOID__USE2_HANDWASH20    0.1445860  behavior
9  net_g05_w55_high__SEVERITY__USE2_AVOID           0.1407643  belief
10 net_g05_w55_high__SEVERITY__USE2_SPACE150        0.1274139  belief
   to_domain from_role    to_role
1  affect    non_focal    non_focal
2  behavior  non_focal    non_focal
3  behavior  non_focal    non_focal
4  behavior  non_focal    non_focal
5  belief    non_focal    focal_belief
6  behavior  non_focal    non_focal
7  affect    non_focal    non_focal
8  behavior  non_focal    non_focal
9  behavior  focal_belief non_focal
10 behavior  focal_belief non_focal

In [5]:
# ── Bridge edges: belief/affect ↔ behavior ────────────────────────────────────
bridge_df <- edges_all %>%
  filter(
    (from_domain %in% c("belief", "affect") & to_domain == "behavior") |
    (from_domain == "behavior"              & to_domain %in% c("belief", "affect"))
  ) %>%
  arrange(spec, wave, trust_stratum, desc(abs_weight))

write_csv(bridge_df, file.path(NETWORK_DIR, "bridge_edges.csv"))
cat("Saved: bridge_edges.csv —", nrow(bridge_df), "rows\n")
head(bridge_df, 10)

Saved: bridge_edges.csv — 181 rows

   wave trust_stratum n_cc spec from            to                  weight
1  55   high          309  g05  SEVERITY        USE2_AVOID           0.14076434
2  55   high          309  g05  SEVERITY        USE2_SPACE150        0.12741391
3  55   high          309  g05  SEVERITY        USE2_MASK           -0.08060195
4  55   high          309  g05  USE2_MASK       WORRY_HEALTH_SYSTEM  0.07801505
5  55   high          309  g05  AFF_FEAR        USE2_AVOID           0.07112662
6  55   high          309  g05  SEVERITY        USE2_HANDWASH20      0.03889617
7  55   high          309  g05  AFF_WORRY       USE2_AVOID           0.03485093
8  55   high          309  g05  USE2_AVOID      WORRY_HEALTH_SYSTEM  0.03478318
9  55   high          309  g05  AFF_WORRY       USE2_HANDWASH20      0.03162142
10 55   high          309  g05  USE2_HANDWASH20 WORRY_HEALTH_SYSTEM  0.02951233
   spec_id  gamma_ebic thresholded ⋯ context_id   network_id
1  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
2  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
3  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
4  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
5  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
6  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
7  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
8  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
9  gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
10 gamma_05 0.5        FALSE       ⋯ ctx_w55_high net_g05_w55_high
   edge_a          edge_b
1  SEVERITY        USE2_AVOID
2  SEVERITY        USE2_SPACE150
3  SEVERITY        USE2_MASK
4  USE2_MASK       WORRY_HEALTH_SYSTEM
5  AFF_FEAR        USE2_AVOID
6  SEVERITY        USE2_HANDWASH20
7  AFF_WORRY       USE2_AVOID
8  USE2_AVOID      WORRY_HEALTH_SYSTEM
9  AFF_WORRY       USE2_HANDWASH20
10 USE2_HANDWASH20 WORRY_HEALTH_SYSTEM
   edge_id                                                abs_weight
1  net_g05_w55_high__SEVERITY__USE2_AVOID                 0.14076434
2  net_g05_w55_high__SEVERITY__USE2_SPACE150              0.12741391
3  net_g05_w55_high__SEVERITY__USE2_MASK                  0.08060195
4  net_g05_w55_high__USE2_MASK__WORRY_HEALTH_SYSTEM       0.07801505
5  net_g05_w55_high__AFF_FEAR__USE2_AVOID                 0.07112662
6  net_g05_w55_high__SEVERITY__USE2_HANDWASH20            0.03889617
7  net_g05_w55_high__AFF_WORRY__USE2_AVOID                0.03485093
8  net_g05_w55_high__USE2_AVOID__WORRY_HEALTH_SYSTEM      0.03478318
9  net_g05_w55_high__AFF_WORRY__USE2_HANDWASH20           0.03162142
10 net_g05_w55_high__USE2_HANDWASH20__WORRY_HEALTH_SYSTEM 0.02951233
   from_domain to_domain from_role    to_role
1  belief      behavior  focal_belief non_focal
2  belief      behavior  focal_belief non_focal
3  belief      behavior  focal_belief non_focal
4  behavior    affect    non_focal    non_focal
5  affect      behavior  non_focal    non_focal
6  belief      behavior  focal_belief non_focal
7  affect      behavior  non_focal    non_focal
8  behavior    affect    non_focal    non_focal
9  affect      behavior  non_focal    non_focal
10 behavior    affect    non_focal    non_focal

In [6]:
# ── Node metrics: degree and strength from adjacency matrices ─────────────────
# Adjacency matrices are read directly (rather than re-deriving from edge lists)
# to stay faithful to the exported estimation output.
# Diagonal is zeroed before computing degree and strength.

node_metrics <- adj_meta %>%
  mutate(
    W = map(path, function(p) {
      M <- as.matrix(read.csv(p, row.names = 1, check.names = FALSE))
      # Enforce canonical node order; stop if nodes are missing or extra
      if (!all(NODE_VARS %in% rownames(M)))
        stop("Adj matrix ", basename(p), " is missing expected nodes.")
      M <- M[NODE_VARS, NODE_VARS, drop = FALSE]
      diag(M) <- 0
      M
    })
  ) %>%
  mutate(
    node_stats = map(W, function(M) {
      tibble(
        node     = NODE_VARS,
        node_id  = NODE_VARS,
        degree   = as.integer(rowSums(M != 0)),
        strength = as.numeric(rowSums(abs(M)))
      )
    })
  ) %>%
  select(spec, wave, trust_stratum, n_cc, node_stats) %>%
  unnest(node_stats) %>%
  left_join(GAMMA_LOOKUP, by = "spec") %>%
  mutate(
    context_id = paste0("ctx_w", wave, "_", trust_stratum),
    network_id = paste0("net_", spec, "_w", wave, "_", trust_stratum),
    domain     = NODE_DOMAIN[node],
    role       = NODE_ROLE[node]
  ) %>%
  arrange(spec, wave, trust_stratum, domain, node)

write_csv(node_metrics, file.path(NETWORK_DIR, "node_metrics.csv"))
cat("Saved: node_metrics.csv —", nrow(node_metrics), "rows\n")
head(node_metrics, 10)

Saved: node_metrics.csv — 192 rows

   spec wave trust_stratum n_cc node                node_id             degree
1  g05  55   high          309  AFF_FEAR            AFF_FEAR            6
2  g05  55   high          309  AFF_WORRY           AFF_WORRY           5
3  g05  55   high          309  WORRY_HEALTH_SYSTEM WORRY_HEALTH_SYSTEM 7
4  g05  55   high          309  USE2_AVOID          USE2_AVOID          7
5  g05  55   high          309  USE2_HANDWASH20     USE2_HANDWASH20     7
6  g05  55   high          309  USE2_MASK           USE2_MASK           6
7  g05  55   high          309  USE2_SPACE150       USE2_SPACE150       5
8  g05  55   high          309  SEVERITY            SEVERITY            7
9  g05  55   low           376  AFF_FEAR            AFF_FEAR            4
10 g05  55   low           376  AFF_WORRY           AFF_WORRY           6
   strength  spec_id  gamma_ebic thresholded cor_method in_kg context_id
1  1.0544797 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_high
2  0.7797262 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_high
3  0.5169383 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_high
4  0.7157924 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_high
5  0.6438941 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_high
6  0.6262256 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_high
7  0.8069789 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_high
8  0.7528890 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_high
9  1.0237396 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_low
10 0.8947345 gamma_05 0.5        FALSE       pearson    TRUE  ctx_w55_low
   network_id       domain   role
1  net_g05_w55_high affect   non_focal
2  net_g05_w55_high affect   non_focal
3  net_g05_w55_high affect   non_focal
4  net_g05_w55_high behavior non_focal
5  net_g05_w55_high behavior non_focal
6  net_g05_w55_high behavior non_focal
7  net_g05_w55_high behavior non_focal
8  net_g05_w55_high belief   focal_belief
9  net_g05_w55_low  affect   non_focal
10 net_g05_w55_low  affect   non_focal

In [7]:
# ── Context-level summary ─────────────────────────────────────────────────────
edge_counts <- edges_all %>%
  mutate(
    is_bridge = (from %in% PSY_NODES & to %in% BEH_NODES) |
                (from %in% BEH_NODES & to %in% PSY_NODES)
  ) %>%
  group_by(spec, wave, trust_stratum, n_cc) %>%
  summarise(
    n_edges_nonzero = n(),
    n_bridge_edges  = sum(is_bridge),
    .groups = "drop"
  )

beh_agg <- node_metrics %>%
  filter(domain == "behavior") %>%
  group_by(spec, wave, trust_stratum, n_cc) %>%
  summarise(
    beh_degree_mean   = mean(degree),
    beh_degree_min    = min(degree),
    beh_strength_mean = mean(strength),
    .groups = "drop"
  )

context_summary <- edge_counts %>%
  left_join(beh_agg, by = c("spec","wave","trust_stratum","n_cc")) %>%
  left_join(GAMMA_LOOKUP, by = "spec") %>%
  mutate(
    context_id = paste0("ctx_w", wave, "_", trust_stratum),
    network_id = paste0("net_", spec, "_w", wave, "_", trust_stratum)
  ) %>%
  arrange(spec, wave, trust_stratum)

write_csv(context_summary, file.path(NETWORK_DIR, "context_summary.csv"))
cat("Saved: context_summary.csv —", nrow(context_summary), "rows\n")
context_summary

Saved: context_summary.csv — 24 rows

   spec         wave trust_stratum n_cc n_edges_nonzero n_bridge_edges
1  g05          55   high          309  25              13
2  g05          55   low           376  23              11
3  g05          56   high          351  21              10
4  g05          56   low           383  21               9
5  g05          57   high          407  17               6
6  g05          57   low           336  22              10
7  g05_spearman 55   high          309  23              11
8  g05_spearman 55   low           376  23              11
9  g05_spearman 56   high          351  22              10
10 g05_spearman 56   low           383  20               8
11 g05_spearman 57   high          407  16               5
12 g05_spearman 57   low           336  20               8
13 g05_thr      55   high          309   9               2
14 g05_thr      55   low           376  14               3
15 g05_thr      56   high          351   9               1
16 g05_thr      56   low           383  12               2
17 g05_thr      57   high          407   6               1
18 g05_thr      57   low           336  12               3
19 g075         55   high          309  23              11
20 g075         55   low           376  23              11
21 g075         56   high          351  21              10
22 g075         56   low           383  21               9
23 g075         57   high          407  17               6
24 g075         57   low           336  22              10
   beh_degree_mean beh_degree_min beh_strength_mean spec_id
1  6.25            5              0.6982227         gamma_05
2  5.75            5              0.7857290         gamma_05
3  5.50            4              0.6916435         gamma_05
4  5.25            3              0.7482350         gamma_05
5  4.50            4              0.4964156         gamma_05
6  5.50            4              0.8297972         gamma_05
7  5.75            5              0.6277178         gamma_05_spearman
8  5.75            5              0.8337819         gamma_05_spearman
9  5.50            4              0.7252624         gamma_05_spearman
10 5.00            3              0.7510329         gamma_05_spearman
11 4.25            4              0.3850411         gamma_05_spearman
12 5.00            3              0.7979707         gamma_05_spearman
13 2.50            2              0.5226238         gamma_05_thr
14 3.75            3              0.7548828         gamma_05_thr
15 2.75            2              0.5837584         gamma_05_thr
16 3.00            3              0.6845737         gamma_05_thr
17 1.25            1              0.2844100         gamma_05_thr
18 3.25            3              0.7669411         gamma_05_thr
19 5.75            4              0.6090276         gamma_075
20 5.75            5              0.7857290         gamma_075
21 5.50            4              0.6916435         gamma_075
22 5.25            3              0.7482350         gamma_075
23 4.50            4              0.4964156         gamma_075
24 5.50            4              0.8297972         gamma_075
   gamma_ebic thresholded cor_method in_kg context_id
1  0.50       FALSE       pearson     TRUE ctx_w55_high
2  0.50       FALSE       pearson     TRUE ctx_w55_low
3  0.50       FALSE       pearson     TRUE ctx_w56_high
4  0.50       FALSE       pearson     TRUE ctx_w56_low
5  0.50       FALSE       pearson     TRUE ctx_w57_high
6  0.50       FALSE       pearson     TRUE ctx_w57_low
7  0.50       FALSE       spearman   FALSE ctx_w55_high
8  0.50       FALSE       spearman   FALSE ctx_w55_low
9  0.50       FALSE       spearman   FALSE ctx_w56_high
10 0.50       FALSE       spearman   FALSE ctx_w56_low
11 0.50       FALSE       spearman   FALSE ctx_w57_high
12 0.50       FALSE       spearman   FALSE ctx_w57_low
13 0.50        TRUE       pearson    FALSE ctx_w55_high
14 0.50        TRUE       pearson    FALSE ctx_w55_low
15 0.50        TRUE       pearson    FALSE ctx_w56_high
16 0.50        TRUE       pearson    FALSE ctx_w56_low
17 0.50        TRUE       pearson    FALSE ctx_w57_high
18 0.50        TRUE       pearson    FALSE ctx_w57_low
19 0.75       FALSE       pearson    FALSE ctx_w55_high
20 0.75       FALSE       pearson    FALSE ctx_w55_low
21 0.75       FALSE       pearson    FALSE ctx_w56_high
22 0.75       FALSE       pearson    FALSE ctx_w56_low
23 0.75       FALSE       pearson    FALSE ctx_w57_high
24 0.75       FALSE       pearson    FALSE ctx_w57_low
   network_id
1  net_g05_w55_high
2  net_g05_w55_low
3  net_g05_w56_high
4  net_g05_w56_low
5  net_g05_w57_high
6  net_g05_w57_low
7  net_g05_spearman_w55_high
8  net_g05_spearman_w55_low
9  net_g05_spearman_w56_high
10 net_g05_spearman_w56_low
11 net_g05_spearman_w57_high
12 net_g05_spearman_w57_low
13 net_g05_thr_w55_high
14 net_g05_thr_w55_low
15 net_g05_thr_w56_high
16 net_g05_thr_w56_low
17 net_g05_thr_w57_high
18 net_g05_thr_w57_low
19 net_g075_w55_high
20 net_g075_w55_low
21 net_g075_w56_high
22 net_g075_w56_low
23 net_g075_w57_high
24 net_g075_w57_low

In [8]:
# ── Edge-weight differences: high − low trust, within wave ───────────────────
# For each wave × spec pair, compute element-wise (W_high − W_low) on the
# upper-triangle of the adjacency matrix.
# Pairs where the difference is exactly zero (both networks agree) are retained
# with diff = 0; we filter ONLY at display time if needed, not at save time.
# This preserves complete information in the exported file.

adj_lookup <- adj_meta %>% select(spec, wave, trust_stratum, n_cc, path)

load_adj <- function(meta_row) {
  M <- as.matrix(read.csv(meta_row$path, row.names = 1, check.names = FALSE))
  M[NODE_VARS, NODE_VARS, drop = FALSE]
}

pairs <- adj_lookup %>%
  group_by(spec, wave) %>%
  summarise(
    has_low  = any(trust_stratum == "low"),
    has_high = any(trust_stratum == "high"),
    .groups  = "drop"
  ) %>%
  filter(has_low, has_high) %>%
  select(spec, wave)

diff_all <- map_dfr(seq_len(nrow(pairs)), function(i) {
  sp <- pairs$spec[i]
  wv <- pairs$wave[i]

  low_row  <- filter(adj_lookup, spec == sp, wave == wv, trust_stratum == "low")  %>% slice(1)
  high_row <- filter(adj_lookup, spec == sp, wave == wv, trust_stratum == "high") %>% slice(1)

  W_low  <- load_adj(low_row)
  W_high <- load_adj(high_row)

  D   <- W_high - W_low
  idx <- which(upper.tri(D), arr.ind = TRUE)

  tibble(
    spec                      = sp,
    wave                      = wv,
    from                      = NODE_VARS[idx[, 1]],
    to                        = NODE_VARS[idx[, 2]],
    diff_weight_high_minus_low = as.numeric(D[idx]),
    abs_diff                  = abs(as.numeric(D[idx])),
    n_low                     = low_row$n_cc,
    n_high                    = high_row$n_cc,
    from_domain               = NODE_DOMAIN[NODE_VARS[idx[, 1]]],
    to_domain                 = NODE_DOMAIN[NODE_VARS[idx[, 2]]],
    from_role                 = NODE_ROLE[NODE_VARS[idx[, 1]]],
    to_role                   = NODE_ROLE[NODE_VARS[idx[, 2]]]
  )
}) %>%
  left_join(GAMMA_LOOKUP, by = "spec") %>%
  mutate(comparison_id = paste0("diff_", spec, "_w", wave, "_high_minus_low")) %>%
  arrange(spec, wave, desc(abs_diff))

write_csv(diff_all, file.path(NETWORK_DIR, "edge_differences_high_minus_low.csv"))
cat("Saved: edge_differences_high_minus_low.csv —", nrow(diff_all), "rows\n")

# Show only non-zero differences for inspection
diff_all %>% filter(abs_diff > 0) %>% head(20)

Saved: edge_differences_high_minus_low.csv — 336 rows

   spec wave from                to                  diff_weight_high_minus_low
1  g05  55   SEVERITY            USE2_AVOID           0.12576886
2  g05  55   SEVERITY            USE2_SPACE150        0.11373258
3  g05  55   USE2_MASK           USE2_SPACE150       -0.11344080
4  g05  55   WORRY_HEALTH_SYSTEM USE2_HANDWASH20     -0.11261567
5  g05  55   USE2_MASK           USE2_AVOID          -0.10658093
6  g05  55   SEVERITY            USE2_MASK           -0.09792896
7  g05  55   SEVERITY            WORRY_HEALTH_SYSTEM -0.08422747
8  g05  55   AFF_FEAR            WORRY_HEALTH_SYSTEM  0.08209579
9  g05  55   SEVERITY            AFF_FEAR            -0.07143053
10 g05  55   AFF_WORRY           USE2_SPACE150       -0.07054136
11 g05  55   WORRY_HEALTH_SYSTEM USE2_MASK           -0.06068863
12 g05  55   AFF_WORRY           WORRY_HEALTH_SYSTEM -0.04156687
13 g05  55   USE2_SPACE150       USE2_AVOID          -0.03915507
14 g05  55   AFF_FEAR            USE2_AVOID          -0.03624115
15 g05  55   USE2_MASK           USE2_HANDWASH20      0.03614563
16 g05  55   SEVERITY            USE2_HANDWASH20      0.03426530
17 g05  55   AFF_WORRY           USE2_HANDWASH20      0.03162142
18 g05  55   AFF_WORRY           USE2_AVOID          -0.02763518
19 g05  55   USE2_SPACE150       USE2_HANDWASH20     -0.02705636
20 g05  55   WORRY_HEALTH_SYSTEM USE2_SPACE150        0.02466880
   abs_diff   n_low n_high from_domain to_domain from_role    to_role
1  0.12576886 376   309    belief      behavior  focal_belief non_focal
2  0.11373258 376   309    belief      behavior  focal_belief non_focal
3  0.11344080 376   309    behavior    behavior  non_focal    non_focal
4  0.11261567 376   309    affect      behavior  non_focal    non_focal
5  0.10658093 376   309    behavior    behavior  non_focal    non_focal
6  0.09792896 376   309    belief      behavior  focal_belief non_focal
7  0.08422747 376   309    belief      affect    focal_belief non_focal
8  0.08209579 376   309    affect      affect    non_focal    non_focal
9  0.07143053 376   309    belief      affect    focal_belief non_focal
10 0.07054136 376   309    affect      behavior  non_focal    non_focal
11 0.06068863 376   309    affect      behavior  non_focal    non_focal
12 0.04156687 376   309    affect      affect    non_focal    non_focal
13 0.03915507 376   309    behavior    behavior  non_focal    non_focal
14 0.03624115 376   309    affect      behavior  non_focal    non_focal
15 0.03614563 376   309    behavior    behavior  non_focal    non_focal
16 0.03426530 376   309    belief      behavior  focal_belief non_focal
17 0.03162142 376   309    affect      behavior  non_focal    non_focal
18 0.02763518 376   309    affect      behavior  non_focal    non_focal
19 0.02705636 376   309    behavior    behavior  non_focal    non_focal
20 0.02466880 376   309    affect      behavior  non_focal    non_focal
   spec_id  gamma_ebic thresholded cor_method in_kg comparison_id
1  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
2  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
3  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
4  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
5  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
6  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
7  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
8  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
9  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
10 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
11 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
12 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
13 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
14 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
15 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
16 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
17 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
18 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
19 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
20 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low

In [9]:
# ── Bridge-edge differences subset ───────────────────────────────────────────
bridge_diff <- diff_all %>%
  filter(
    (from_domain %in% c("belief", "affect") & to_domain == "behavior") |
    (from_domain == "behavior"              & to_domain %in% c("belief", "affect"))
  ) %>%
  arrange(spec, wave, desc(abs_diff))

write_csv(bridge_diff, file.path(NETWORK_DIR, "bridge_differences_high_minus_low.csv"))
cat("Saved: bridge_differences_high_minus_low.csv —", nrow(bridge_diff), "rows\n")
bridge_diff %>% filter(abs_diff > 0) %>% head(20)

Saved: bridge_differences_high_minus_low.csv — 192 rows

   spec wave from                to              diff_weight_high_minus_low
1  g05  55   SEVERITY            USE2_AVOID       0.125768865
2  g05  55   SEVERITY            USE2_SPACE150    0.113732578
3  g05  55   WORRY_HEALTH_SYSTEM USE2_HANDWASH20 -0.112615672
4  g05  55   SEVERITY            USE2_MASK       -0.097928962
5  g05  55   AFF_WORRY           USE2_SPACE150   -0.070541362
6  g05  55   WORRY_HEALTH_SYSTEM USE2_MASK       -0.060688631
7  g05  55   AFF_FEAR            USE2_AVOID      -0.036241155
8  g05  55   SEVERITY            USE2_HANDWASH20  0.034265297
9  g05  55   AFF_WORRY           USE2_HANDWASH20  0.031621419
10 g05  55   AFF_WORRY           USE2_AVOID      -0.027635184
11 g05  55   WORRY_HEALTH_SYSTEM USE2_SPACE150    0.024668800
12 g05  55   AFF_FEAR            USE2_MASK        0.019015543
13 g05  55   AFF_WORRY           USE2_MASK       -0.015562824
14 g05  55   AFF_FEAR            USE2_HANDWASH20  0.012653036
15 g05  55   WORRY_HEALTH_SYSTEM USE2_AVOID       0.003139369
16 g05  56   AFF_WORRY           USE2_MASK       -0.122296617
17 g05  56   SEVERITY            USE2_HANDWASH20  0.103265974
18 g05  56   WORRY_HEALTH_SYSTEM USE2_AVOID       0.087589861
19 g05  56   WORRY_HEALTH_SYSTEM USE2_HANDWASH20  0.076658233
20 g05  56   AFF_WORRY           USE2_AVOID       0.068561594
   abs_diff    n_low n_high from_domain to_domain from_role    to_role
1  0.125768865 376   309    belief      behavior  focal_belief non_focal
2  0.113732578 376   309    belief      behavior  focal_belief non_focal
3  0.112615672 376   309    affect      behavior  non_focal    non_focal
4  0.097928962 376   309    belief      behavior  focal_belief non_focal
5  0.070541362 376   309    affect      behavior  non_focal    non_focal
6  0.060688631 376   309    affect      behavior  non_focal    non_focal
7  0.036241155 376   309    affect      behavior  non_focal    non_focal
8  0.034265297 376   309    belief      behavior  focal_belief non_focal
9  0.031621419 376   309    affect      behavior  non_focal    non_focal
10 0.027635184 376   309    affect      behavior  non_focal    non_focal
11 0.024668800 376   309    affect      behavior  non_focal    non_focal
12 0.019015543 376   309    affect      behavior  non_focal    non_focal
13 0.015562824 376   309    affect      behavior  non_focal    non_focal
14 0.012653036 376   309    affect      behavior  non_focal    non_focal
15 0.003139369 376   309    affect      behavior  non_focal    non_focal
16 0.122296617 383   351    affect      behavior  non_focal    non_focal
17 0.103265974 383   351    belief      behavior  focal_belief non_focal
18 0.087589861 383   351    affect      behavior  non_focal    non_focal
19 0.076658233 383   351    affect      behavior  non_focal    non_focal
20 0.068561594 383   351    affect      behavior  non_focal    non_focal
   spec_id  gamma_ebic thresholded cor_method in_kg comparison_id
1  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
2  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
3  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
4  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
5  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
6  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
7  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
8  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
9  gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
10 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
11 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
12 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
13 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
14 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
15 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w55_high_minus_low
16 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w56_high_minus_low
17 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w56_high_minus_low
18 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w56_high_minus_low
19 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w56_high_minus_low
20 gamma_05 0.5        FALSE       pearson    TRUE  diff_g05_w56_high_minus_low

In [10]:
# ── Focal-belief bridges: SEVERITY ↔ behavior ────────────────────────────────
# Subset of bridge_df where one endpoint is the focal belief node.
focal_bridge <- bridge_df %>%
  filter(
    (from == FOCAL_NODE & to_domain   == "behavior") |
    (to   == FOCAL_NODE & from_domain == "behavior")
  ) %>%
  arrange(spec, wave, trust_stratum, desc(abs_weight))

write_csv(focal_bridge, file.path(NETWORK_DIR, "focal_belief_bridges.csv"))
cat("Saved: focal_belief_bridges.csv —", nrow(focal_bridge), "rows\n")
focal_bridge

Saved: focal_belief_bridges.csv — 47 rows

   wave trust_stratum n_cc spec         from     to              weight
1  55   high          309  g05          SEVERITY USE2_AVOID       0.140764339
2  55   high          309  g05          SEVERITY USE2_SPACE150    0.127413906
3  55   high          309  g05          SEVERITY USE2_MASK       -0.080601952
4  55   high          309  g05          SEVERITY USE2_HANDWASH20  0.038896167
5  55   low           376  g05          SEVERITY USE2_MASK        0.017327010
6  55   low           376  g05          SEVERITY USE2_AVOID       0.014995474
7  55   low           376  g05          SEVERITY USE2_SPACE150    0.013681328
8  55   low           376  g05          SEVERITY USE2_HANDWASH20  0.004630871
9  56   high          351  g05          SEVERITY USE2_AVOID       0.127075034
10 56   high          351  g05          SEVERITY USE2_HANDWASH20  0.103265974
11 56   high          351  g05          SEVERITY USE2_SPACE150    0.065477835
12 56   low           383  g05          SEVERITY USE2_AVOID       0.146667667
13 56   low           383  g05          SEVERITY USE2_SPACE150    0.027484036
14 57   high          407  g05          SEVERITY USE2_HANDWASH20  0.040816025
15 57   low           336  g05          SEVERITY USE2_AVOID       0.095056513
16 57   low           336  g05          SEVERITY USE2_SPACE150    0.051837600
17 55   high          309  g05_spearman SEVERITY USE2_SPACE150    0.118697358
18 55   high          309  g05_spearman SEVERITY USE2_AVOID       0.105482278
19 55   high          309  g05_spearman SEVERITY USE2_HANDWASH20  0.037450202
20 55   low           376  g05_spearman SEVERITY USE2_HANDWASH20  0.031352441
21 55   low           376  g05_spearman SEVERITY USE2_SPACE150    0.014767945
22 55   low           376  g05_spearman SEVERITY USE2_AVOID       0.011971983
23 56   high          351  g05_spearman SEVERITY USE2_AVOID       0.138243245
24 56   high          351  g05_spearman SEVERITY USE2_SPACE150    0.085282586
25 56   high          351  g05_spearman SEVERITY USE2_HANDWASH20  0.067878048
26 56   low           383  g05_spearman SEVERITY USE2_AVOID       0.158154121
27 57   low           336  g05_spearman SEVERITY USE2_AVOID       0.098546396
28 57   low           336  g05_spearman SEVERITY USE2_SPACE150    0.014977219
29 55   high          309  g05_thr      SEVERITY USE2_SPACE150    0.168294034
30 55   high          309  g05_thr      SEVERITY USE2_AVOID       0.142459761
31 56   high          351  g05_thr      SEVERITY USE2_HANDWASH20  0.147617307
32 56   low           383  g05_thr      SEVERITY USE2_AVOID       0.153446109
33 55   high          309  g075         SEVERITY USE2_AVOID       0.128780971
34 55   high          309  g075         SEVERITY USE2_SPACE150    0.103125871
35 55   high          309  g075         SEVERITY USE2_HANDWASH20  0.018838231
36 55   low           376  g075         SEVERITY USE2_MASK        0.017327010
37 55   low           376  g075         SEVERITY USE2_AVOID       0.014995474
38 55   low           376  g075         SEVERITY USE2_SPACE150    0.013681328
39 55   low           376  g075         SEVERITY USE2_HANDWASH20  0.004630871
40 56   high          351  g075         SEVERITY USE2_AVOID       0.127075034
41 56   high          351  g075         SEVERITY USE2_HANDWASH20  0.103265974
42 56   high          351  g075         SEVERITY USE2_SPACE150    0.065477835
43 56   low           383  g075         SEVERITY USE2_AVOID       0.146667667
44 56   low           383  g075         SEVERITY USE2_SPACE150    0.027484036
45 57   high          407  g075         SEVERITY USE2_HANDWASH20  0.040816025
46 57   low           336  g075         SEVERITY USE2_AVOID       0.095056513
47 57   low           336  g075         SEVERITY USE2_SPACE150    0.051837600
   spec_id           gamma_ebic thresholded ⋯ context_id
1  gamma_05          0.50       FALSE       ⋯ ctx_w55_high
2  gamma_05          0.50       FALSE       ⋯ ctx_w55_high
3  gamma_05          0.50       FALSE       ⋯ ctx_w55_high
4  gamma_05          0.50       FALSE       ⋯ ctx_w55_high
5  gamma_05          0.50       FALSE       ⋯ ctx_w55_low
6  gamma_05          0.50       FALSE       ⋯ ctx_w55_low
7  gamma_05          0.50       FALSE       ⋯ ctx_w55_low
8  gamma_05          0.50       FALSE       ⋯ ctx_w55_low
9  gamma_05          0.50       FALSE       ⋯ ctx_w56_high
10 gamma_05          0.50       FALSE       ⋯ ctx_w56_high
11 gamma_05          0.50       FALSE       ⋯ ctx_w56_high
12 gamma_05          0.50       FALSE       ⋯ ctx_w56_low
13 gamma_05          0.50       FALSE       ⋯ ctx_w56_low
14 gamma_05          0.50       FALSE       ⋯ ctx_w57_high
15 gamma_05          0.50       FALSE       ⋯ ctx_w57_low
16 gamma_05          0.50       FALSE       ⋯ ctx_w57_low
17 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w55_high
18 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w55_high
19 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w55_high
20 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w55_low
21 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w55_low
22 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w55_low
23 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w56_high
24 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w56_high
25 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w56_high
26 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w56_low
27 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w57_low
28 gamma_05_spearman 0.50       FALSE       ⋯ ctx_w57_low
29 gamma_05_thr      0.50        TRUE       ⋯ ctx_w55_high
30 gamma_05_thr      0.50        TRUE       ⋯ ctx_w55_high
31 gamma_05_thr      0.50        TRUE       ⋯ ctx_w56_high
32 gamma_05_thr      0.50        TRUE       ⋯ ctx_w56_low
33 gamma_075         0.75       FALSE       ⋯ ctx_w55_high
34 gamma_075         0.75       FALSE       ⋯ ctx_w55_high
35 gamma_075         0.75       FALSE       ⋯ ctx_w55_high
36 gamma_075         0.75       FALSE       ⋯ ctx_w55_low
37 gamma_075         0.75       FALSE       ⋯ ctx_w55_low
38 gamma_075         0.75       FALSE       ⋯ ctx_w55_low
39 gamma_075         0.75       FALSE       ⋯ ctx_w55_low
40 gamma_075         0.75       FALSE       ⋯ ctx_w56_high
41 gamma_075         0.75       FALSE       ⋯ ctx_w56_high
42 gamma_075         0.75       FALSE       ⋯ ctx_w56_high
43 gamma_075         0.75       FALSE       ⋯ ctx_w56_low
44 gamma_075         0.75       FALSE       ⋯ ctx_w56_low
45 gamma_075         0.75       FALSE       ⋯ ctx_w57_high
46 gamma_075         0.75       FALSE       ⋯ ctx_w57_low
47 gamma_075         0.75       FALSE       ⋯ ctx_w57_low
   network_id                edge_a   edge_b
1  net_g05_w55_high          SEVERITY USE2_AVOID
2  net_g05_w55_high          SEVERITY USE2_SPACE150
3  net_g05_w55_high          SEVERITY USE2_MASK
4  net_g05_w55_high          SEVERITY USE2_HANDWASH20
5  net_g05_w55_low           SEVERITY USE2_MASK
6  net_g05_w55_low           SEVERITY USE2_AVOID
7  net_g05_w55_low           SEVERITY USE2_SPACE150
8  net_g05_w55_low           SEVERITY USE2_HANDWASH20
9  net_g05_w56_high          SEVERITY USE2_AVOID
10 net_g05_w56_high          SEVERITY USE2_HANDWASH20
11 net_g05_w56_high          SEVERITY USE2_SPACE150
12 net_g05_w56_low           SEVERITY USE2_AVOID
13 net_g05_w56_low           SEVERITY USE2_SPACE150
14 net_g05_w57_high          SEVERITY USE2_HANDWASH20
15 net_g05_w57_low           SEVERITY USE2_AVOID
16 net_g05_w57_low           SEVERITY USE2_SPACE150
17 net_g05_spearman_w55_high SEVERITY USE2_SPACE150
18 net_g05_spearman_w55_high SEVERITY USE2_AVOID
19 net_g05_spearman_w55_high SEVERITY USE2_HANDWASH20
20 net_g05_spearman_w55_low  SEVERITY USE2_HANDWASH20
21 net_g05_spearman_w55_low  SEVERITY USE2_SPACE150
22 net_g05_spearman_w55_low  SEVERITY USE2_AVOID
23 net_g05_spearman_w56_high SEVERITY USE2_AVOID
24 net_g05_spearman_w56_high SEVERITY USE2_SPACE150
25 net_g05_spearman_w56_high SEVERITY USE2_HANDWASH20
26 net_g05_spearman_w56_low  SEVERITY USE2_AVOID
27 net_g05_spearman_w57_low  SEVERITY USE2_AVOID
28 net_g05_spearman_w57_low  SEVERITY USE2_SPACE150
29 net_g05_thr_w55_high      SEVERITY USE2_SPACE150
30 net_g05_thr_w55_high      SEVERITY USE2_AVOID
31 net_g05_thr_w56_high      SEVERITY USE2_HANDWASH20
32 net_g05_thr_w56_low       SEVERITY USE2_AVOID
33 net_g075_w55_high         SEVERITY USE2_AVOID
34 net_g075_w55_high         SEVERITY USE2_SPACE150
35 net_g075_w55_high         SEVERITY USE2_HANDWASH20
36 net_g075_w55_low          SEVERITY USE2_MASK
37 net_g075_w55_low          SEVERITY USE2_AVOID
38 net_g075_w55_low          SEVERITY USE2_SPACE150
39 net_g075_w55_low          SEVERITY USE2_HANDWASH20
40 net_g075_w56_high         SEVERITY USE2_AVOID
41 net_g075_w56_high         SEVERITY USE2_HANDWASH20
42 net_g075_w56_high         SEVERITY USE2_SPACE150
43 net_g075_w56_low          SEVERITY USE2_AVOID
44 net_g075_w56_low          SEVERITY USE2_SPACE150
45 net_g075_w57_high         SEVERITY USE2_HANDWASH20
46 net_g075_w57_low          SEVERITY USE2_AVOID
47 net_g075_w57_low          SEVERITY USE2_SPACE150
   edge_id                                              abs_weight  from_domain
1  net_g05_w55_high__SEVERITY__USE2_AVOID               0.140764339 belief
2  net_g05_w55_high__SEVERITY__USE2_SPACE150            0.127413906 belief
3  net_g05_w55_high__SEVERITY__USE2_MASK                0.080601952 belief
4  net_g05_w55_high__SEVERITY__USE2_HANDWASH20          0.038896167 belief
5  net_g05_w55_low__SEVERITY__USE2_MASK                 0.017327010 belief
6  net_g05_w55_low__SEVERITY__USE2_AVOID                0.014995474 belief
7  net_g05_w55_low__SEVERITY__USE2_SPACE150             0.013681328 belief
8  net_g05_w55_low__SEVERITY__USE2_HANDWASH20           0.004630871 belief
9  net_g05_w56_high__SEVERITY__USE2_AVOID               0.127075034 belief
10 net_g05_w56_high__SEVERITY__USE2_HANDWASH20          0.103265974 belief
11 net_g05_w56_high__SEVERITY__USE2_SPACE150            0.065477835 belief
12 net_g05_w56_low__SEVERITY__USE2_AVOID                0.146667667 belief
13 net_g05_w56_low__SEVERITY__USE2_SPACE150             0.027484036 belief
14 net_g05_w57_high__SEVERITY__USE2_HANDWASH20          0.040816025 belief
15 net_g05_w57_low__SEVERITY__USE2_AVOID                0.095056513 belief
16 net_g05_w57_low__SEVERITY__USE2_SPACE150             0.051837600 belief
17 net_g05_spearman_w55_high__SEVERITY__USE2_SPACE150   0.118697358 belief
18 net_g05_spearman_w55_high__SEVERITY__USE2_AVOID      0.105482278 belief
19 net_g05_spearman_w55_high__SEVERITY__USE2_HANDWASH20 0.037450202 belief
20 net_g05_spearman_w55_low__SEVERITY__USE2_HANDWASH20  0.031352441 belief
21 net_g05_spearman_w55_low__SEVERITY__USE2_SPACE150    0.014767945 belief
22 net_g05_spearman_w55_low__SEVERITY__USE2_AVOID       0.011971983 belief
23 net_g05_spearman_w56_high__SEVERITY__USE2_AVOID      0.138243245 belief
24 net_g05_spearman_w56_high__SEVERITY__USE2_SPACE150   0.085282586 belief
25 net_g05_spearman_w56_high__SEVERITY__USE2_HANDWASH20 0.067878048 belief
26 net_g05_spearman_w56_low__SEVERITY__USE2_AVOID       0.158154121 belief
27 net_g05_spearman_w57_low__SEVERITY__USE2_AVOID       0.098546396 belief
28 net_g05_spearman_w57_low__SEVERITY__USE2_SPACE150    0.014977219 belief
29 net_g05_thr_w55_high__SEVERITY__USE2_SPACE150        0.168294034 belief
30 net_g05_thr_w55_high__SEVERITY__USE2_AVOID           0.142459761 belief
31 net_g05_thr_w56_high__SEVERITY__USE2_HANDWASH20      0.147617307 belief
32 net_g05_thr_w56_low__SEVERITY__USE2_AVOID            0.153446109 belief
33 net_g075_w55_high__SEVERITY__USE2_AVOID              0.128780971 belief
34 net_g075_w55_high__SEVERITY__USE2_SPACE150           0.103125871 belief
35 net_g075_w55_high__SEVERITY__USE2_HANDWASH20         0.018838231 belief
36 net_g075_w55_low__SEVERITY__USE2_MASK                0.017327010 belief
37 net_g075_w55_low__SEVERITY__USE2_AVOID               0.014995474 belief
38 net_g075_w55_low__SEVERITY__USE2_SPACE150            0.013681328 belief
39 net_g075_w55_low__SEVERITY__USE2_HANDWASH20          0.004630871 belief
40 net_g075_w56_high__SEVERITY__USE2_AVOID              0.127075034 belief
41 net_g075_w56_high__SEVERITY__USE2_HANDWASH20         0.103265974 belief
42 net_g075_w56_high__SEVERITY__USE2_SPACE150           0.065477835 belief
43 net_g075_w56_low__SEVERITY__USE2_AVOID               0.146667667 belief
44 net_g075_w56_low__SEVERITY__USE2_SPACE150            0.027484036 belief
45 net_g075_w57_high__SEVERITY__USE2_HANDWASH20         0.040816025 belief
46 net_g075_w57_low__SEVERITY__USE2_AVOID               0.095056513 belief
47 net_g075_w57_low__SEVERITY__USE2_SPACE150            0.051837600 belief
   to_domain from_role    to_role
1  behavior  focal_belief non_focal
2  behavior  focal_belief non_focal
3  behavior  focal_belief non_focal
4  behavior  focal_belief non_focal
5  behavior  focal_belief non_focal
6  behavior  focal_belief non_focal
7  behavior  focal_belief non_focal
8  behavior  focal_belief non_focal
9  behavior  focal_belief non_focal
10 behavior  focal_belief non_focal
11 behavior  focal_belief non_focal
12 behavior  focal_belief non_focal
13 behavior  focal_belief non_focal
14 behavior  focal_belief non_focal
15 behavior  focal_belief non_focal
16 behavior  focal_belief non_focal
17 behavior  focal_belief non_focal
18 behavior  focal_belief non_focal
19 behavior  focal_belief non_focal
20 behavior  focal_belief non_focal
21 behavior  focal_belief non_focal
22 behavior  focal_belief non_focal
23 behavior  focal_belief non_focal
24 behavior  focal_belief non_focal
25 behavior  focal_belief non_focal
26 behavior  focal_belief non_focal
27 behavior  focal_belief non_focal
28 behavior  focal_belief non_focal
29 behavior  focal_belief non_focal
30 behavior  focal_belief non_focal
31 behavior  focal_belief non_focal
32 behavior  focal_belief non_focal
33 behavior  focal_belief non_focal
34 behavior  focal_belief non_focal
35 behavior  focal_belief non_focal
36 behavior  focal_belief non_focal
37 behavior  focal_belief non_focal
38 behavior  focal_belief non_focal
39 behavior  focal_belief non_focal
40 behavior  focal_belief non_focal
41 behavior  focal_belief non_focal
42 behavior  focal_belief non_focal
43 behavior  focal_belief non_focal
44 behavior  focal_belief non_focal
45 behavior  focal_belief non_focal
46 behavior  focal_belief non_focal
47 behavior  focal_belief non_focal

In [11]:
# ── Top-10 edges per network instance ────────────────────────────────────────
TOP_K <- 10L

top_edges <- edges_all %>%
  group_by(network_id) %>%
  arrange(desc(abs_weight), .by_group = TRUE) %>%
  slice_head(n = TOP_K) %>%
  ungroup() %>%
  arrange(network_id, desc(abs_weight))

write_csv(top_edges, file.path(NETWORK_DIR, paste0("top_edges_top", TOP_K, ".csv")))
cat("Saved: top_edges_top", TOP_K, ".csv —", nrow(top_edges), "rows\n")
head(top_edges, 10)

Saved: top_edges_top 10 .csv — 234 rows

   wave trust_stratum n_cc spec         from            to
1  55   high          309  g05_spearman AFF_FEAR        AFF_WORRY
2  55   high          309  g05_spearman USE2_AVOID      USE2_SPACE150
3  55   high          309  g05_spearman USE2_HANDWASH20 USE2_SPACE150
4  55   high          309  g05_spearman AFF_FEAR        SEVERITY
5  55   high          309  g05_spearman USE2_HANDWASH20 USE2_MASK
6  55   high          309  g05_spearman USE2_MASK       USE2_SPACE150
7  55   high          309  g05_spearman AFF_FEAR        WORRY_HEALTH_SYSTEM
8  55   high          309  g05_spearman AFF_WORRY       WORRY_HEALTH_SYSTEM
9  55   high          309  g05_spearman SEVERITY        USE2_SPACE150
10 55   high          309  g05_spearman USE2_AVOID      USE2_HANDWASH20
   weight    spec_id           gamma_ebic thresholded ⋯ context_id
1  0.5399868 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
2  0.2593841 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
3  0.2051245 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
4  0.1897455 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
5  0.1832288 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
6  0.1328180 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
7  0.1298846 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
8  0.1290801 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
9  0.1186974 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
10 0.1177988 gamma_05_spearman 0.5        FALSE       ⋯ ctx_w55_high
   network_id                edge_a          edge_b
1  net_g05_spearman_w55_high AFF_FEAR        AFF_WORRY
2  net_g05_spearman_w55_high USE2_AVOID      USE2_SPACE150
3  net_g05_spearman_w55_high USE2_HANDWASH20 USE2_SPACE150
4  net_g05_spearman_w55_high AFF_FEAR        SEVERITY
5  net_g05_spearman_w55_high USE2_HANDWASH20 USE2_MASK
6  net_g05_spearman_w55_high USE2_MASK       USE2_SPACE150
7  net_g05_spearman_w55_high AFF_FEAR        WORRY_HEALTH_SYSTEM
8  net_g05_spearman_w55_high AFF_WORRY       WORRY_HEALTH_SYSTEM
9  net_g05_spearman_w55_high SEVERITY        USE2_SPACE150
10 net_g05_spearman_w55_high USE2_AVOID      USE2_HANDWASH20
   edge_id                                                   abs_weight
1  net_g05_spearman_w55_high__AFF_FEAR__AFF_WORRY            0.5399868
2  net_g05_spearman_w55_high__USE2_AVOID__USE2_SPACE150      0.2593841
3  net_g05_spearman_w55_high__USE2_HANDWASH20__USE2_SPACE150 0.2051245
4  net_g05_spearman_w55_high__AFF_FEAR__SEVERITY             0.1897455
5  net_g05_spearman_w55_high__USE2_HANDWASH20__USE2_MASK     0.1832288
6  net_g05_spearman_w55_high__USE2_MASK__USE2_SPACE150       0.1328180
7  net_g05_spearman_w55_high__AFF_FEAR__WORRY_HEALTH_SYSTEM  0.1298846
8  net_g05_spearman_w55_high__AFF_WORRY__WORRY_HEALTH_SYSTEM 0.1290801
9  net_g05_spearman_w55_high__SEVERITY__USE2_SPACE150        0.1186974
10 net_g05_spearman_w55_high__USE2_AVOID__USE2_HANDWASH20    0.1177988
   from_domain to_domain from_role    to_role
1  affect      affect    non_focal    non_focal
2  behavior    behavior  non_focal    non_focal
3  behavior    behavior  non_focal    non_focal
4  affect      belief    non_focal    focal_belief
5  behavior    behavior  non_focal    non_focal
6  behavior    behavior  non_focal    non_focal
7  affect      affect    non_focal    non_focal
8  affect      affect    non_focal    non_focal
9  belief      behavior  focal_belief non_focal
10 behavior    behavior  non_focal    non_focal

In [12]:
# ── Coverage check: contexts present ─────────────────────────────────────────
contexts_found <- edges_all %>%
  distinct(spec, wave, trust_stratum, n_cc) %>%
  left_join(GAMMA_LOOKUP, by = "spec") %>%
  mutate(
    context_id = paste0("ctx_w",  wave, "_", trust_stratum),
    network_id = paste0("net_", spec, "_w", wave, "_", trust_stratum)
  ) %>%
  arrange(spec, wave, trust_stratum)

cat("Contexts in edges_all (spec × wave × trust):", nrow(contexts_found), "\n")
contexts_found

Contexts in edges_all (spec × wave × trust): 24

   spec         wave trust_stratum n_cc spec_id           gamma_ebic
1  g05          55   high          309  gamma_05          0.50
2  g05          55   low           376  gamma_05          0.50
3  g05          56   high          351  gamma_05          0.50
4  g05          56   low           383  gamma_05          0.50
5  g05          57   high          407  gamma_05          0.50
6  g05          57   low           336  gamma_05          0.50
7  g05_spearman 55   high          309  gamma_05_spearman 0.50
8  g05_spearman 55   low           376  gamma_05_spearman 0.50
9  g05_spearman 56   high          351  gamma_05_spearman 0.50
10 g05_spearman 56   low           383  gamma_05_spearman 0.50
11 g05_spearman 57   high          407  gamma_05_spearman 0.50
12 g05_spearman 57   low           336  gamma_05_spearman 0.50
13 g05_thr      55   high          309  gamma_05_thr      0.50
14 g05_thr      55   low           376  gamma_05_thr      0.50
15 g05_thr      56   high          351  gamma_05_thr      0.50
16 g05_thr      56   low           383  gamma_05_thr      0.50
17 g05_thr      57   high          407  gamma_05_thr      0.50
18 g05_thr      57   low           336  gamma_05_thr      0.50
19 g075         55   high          309  gamma_075         0.75
20 g075         55   low           376  gamma_075         0.75
21 g075         56   high          351  gamma_075         0.75
22 g075         56   low           383  gamma_075         0.75
23 g075         57   high          407  gamma_075         0.75
24 g075         57   low           336  gamma_075         0.75
   thresholded cor_method in_kg context_id   network_id
1  FALSE       pearson     TRUE ctx_w55_high net_g05_w55_high
2  FALSE       pearson     TRUE ctx_w55_low  net_g05_w55_low
3  FALSE       pearson     TRUE ctx_w56_high net_g05_w56_high
4  FALSE       pearson     TRUE ctx_w56_low  net_g05_w56_low
5  FALSE       pearson     TRUE ctx_w57_high net_g05_w57_high
6  FALSE       pearson     TRUE ctx_w57_low  net_g05_w57_low
7  FALSE       spearman   FALSE ctx_w55_high net_g05_spearman_w55_high
8  FALSE       spearman   FALSE ctx_w55_low  net_g05_spearman_w55_low
9  FALSE       spearman   FALSE ctx_w56_high net_g05_spearman_w56_high
10 FALSE       spearman   FALSE ctx_w56_low  net_g05_spearman_w56_low
11 FALSE       spearman   FALSE ctx_w57_high net_g05_spearman_w57_high
12 FALSE       spearman   FALSE ctx_w57_low  net_g05_spearman_w57_low
13  TRUE       pearson    FALSE ctx_w55_high net_g05_thr_w55_high
14  TRUE       pearson    FALSE ctx_w55_low  net_g05_thr_w55_low
15  TRUE       pearson    FALSE ctx_w56_high net_g05_thr_w56_high
16  TRUE       pearson    FALSE ctx_w56_low  net_g05_thr_w56_low
17  TRUE       pearson    FALSE ctx_w57_high net_g05_thr_w57_high
18  TRUE       pearson    FALSE ctx_w57_low  net_g05_thr_w57_low
19 FALSE       pearson    FALSE ctx_w55_high net_g075_w55_high
20 FALSE       pearson    FALSE ctx_w55_low  net_g075_w55_low
21 FALSE       pearson    FALSE ctx_w56_high net_g075_w56_high
22 FALSE       pearson    FALSE ctx_w56_low  net_g075_w56_low
23 FALSE       pearson    FALSE ctx_w57_high net_g075_w57_high
24 FALSE       pearson    FALSE ctx_w57_low  net_g075_w57_low

## Bootstrap uncertainty — edge-level stability metrics

Nonparametric bootstrap distributions (stored in `.rds` files) are summarised
to obtain per-edge stability heuristics: bootstrap mean, SD, 95 % percentile CI,
and proportion of bootstrap samples in which the edge is nonzero.

Bootstrap files exist for `g05` and `g075` only.  Edges from `g05_thr` will
have `NA` bootstrap columns in `edge_metrics.csv`, which is correct by design.

**Note on `summarise_boot_object`:** `bootnet` stores results in `bootTable`
(one row per bootstrap × edge) and `sampleTable` (sample estimates).  Column
names differ across `bootnet` versions, so the helper uses a defensive lookup.

In [13]:
# ── Bootstrap edge-stability summary ─────────────────────────────────────────

# Helper: robustly find column name from a set of candidates
find_col <- function(df, candidates) {
  hit <- intersect(candidates, names(df))
  if (length(hit) == 0)
    stop("None of the expected columns found. Available: ",
         paste(names(df), collapse=", "))
  hit[1]
}

summarise_boot_object <- function(path, spec, wave, trust_stratum, n_cc) {
  obj <- readRDS(path)

  bt <- obj$bootTable
  st <- obj$sampleTable
  if (is.null(bt) || is.null(st))
    stop("bootTable or sampleTable missing in: ", basename(path))

  # ── Resolve column names defensively (bootnet version-safe) ────────────────
  bt_from <- find_col(bt, c("node1","from","Var1"))
  bt_to   <- find_col(bt, c("node2","to",  "Var2"))
  bt_val  <- find_col(bt, c("value","Value","stat"))
  bt_type <- intersect(c("type","Type"), names(bt))

  st_from <- find_col(st, c("node1","from","Var1"))
  st_to   <- find_col(st, c("node2","to",  "Var2"))
  st_val  <- find_col(st, c("value","Value","stat"))
  st_type <- intersect(c("type","Type"), names(st))

  # Keep only "edge" rows if a type column exists
  if (length(bt_type) > 0) bt <- bt[bt[[bt_type[1]]] == "edge", , drop=FALSE]
  if (length(st_type) > 0) st <- st[st[[st_type[1]]] == "edge", , drop=FALSE]

  # ── Canonical edge keys (alphabetic min/max) ───────────────────────────────
  bf  <- as.character(bt[[bt_from]]);  bt2 <- as.character(bt[[bt_to]])
  bv  <- as.numeric(bt[[bt_val]])
  k1  <- pmin(bf, bt2);               k2  <- pmax(bf, bt2)
  bt_df <- tibble(edge_a = k1, edge_b = k2, value = bv)

  sf  <- as.character(st[[st_from]]);  st2 <- as.character(st[[st_to]])
  sv  <- as.numeric(st[[st_val]])
  sk1 <- pmin(sf, st2);               sk2 <- pmax(sf, st2)
  sample_tbl <- tibble(edge_a = sk1, edge_b = sk2, sample_weight = sv) %>%
    group_by(edge_a, edge_b) %>%
    summarise(sample_weight = mean(sample_weight, na.rm = TRUE), .groups = "drop")

  # ── Summarise bootstrap distribution per edge ─────────────────────────────
  bt_df %>%
    group_by(edge_a, edge_b) %>%
    summarise(
      boot_mean    = mean(value, na.rm = TRUE),
      boot_sd      = sd(value,   na.rm = TRUE),
      ci_low       = as.numeric(quantile(value, 0.025, na.rm = TRUE)),
      ci_high      = as.numeric(quantile(value, 0.975, na.rm = TRUE)),
      prop_nonzero = mean(value != 0, na.rm = TRUE),
      n_boot       = sum(!is.na(value)),
      .groups      = "drop"
    ) %>%
    left_join(sample_tbl, by = c("edge_a","edge_b")) %>%
    mutate(
      spec          = .env$spec,
      wave          = .env$wave,
      trust_stratum = .env$trust_stratum,
      n_cc          = .env$n_cc
    ) %>%
    left_join(GAMMA_LOOKUP %>% select(spec, spec_id, gamma_ebic), by = "spec") %>%
    mutate(
      context_id = paste0("ctx_w", wave, "_", trust_stratum),
      network_id = paste0("net_", spec, "_w", wave, "_", trust_stratum),
      edge_id    = paste(network_id, edge_a, edge_b, sep = "__"),
      from       = edge_a,
      to         = edge_b
    ) %>%
    select(
      spec, spec_id, gamma_ebic, wave, trust_stratum, n_cc,
      context_id, network_id, edge_id,
      from, to, edge_a, edge_b, sample_weight,
      boot_mean, boot_sd, ci_low, ci_high, prop_nonzero, n_boot
    )
}

if (nrow(boot_meta) == 0) {
  warning("No bootstrap RDS files found. edge_metrics.csv will have NA bootstrap columns.")
  boot_edge_metrics <- tibble(
    spec=character(), spec_id=character(), gamma_ebic=numeric(),
    wave=integer(), trust_stratum=character(), n_cc=integer(),
    context_id=character(), network_id=character(), edge_id=character(),
    from=character(), to=character(), edge_a=character(), edge_b=character(),
    sample_weight=numeric(), boot_mean=numeric(), boot_sd=numeric(),
    ci_low=numeric(), ci_high=numeric(), prop_nonzero=numeric(), n_boot=integer()
  )
} else {
  boot_edge_metrics <- pmap_dfr(
    list(
      path          = boot_meta$path,
      spec          = boot_meta$spec,
      wave          = boot_meta$wave,
      trust_stratum = boot_meta$trust_stratum,
      n_cc          = boot_meta$n_cc
    ),
    summarise_boot_object
  ) %>%
    arrange(spec, wave, trust_stratum, desc(abs(sample_weight)))
}

write_csv(boot_edge_metrics, file.path(NETWORK_DIR, "edge_bootstrap_metrics.csv"))
cat("Saved: edge_bootstrap_metrics.csv —", nrow(boot_edge_metrics), "rows\n")

Saved: edge_bootstrap_metrics.csv — 336 rows

In [14]:
# ── Merge point estimates with bootstrap summaries → edge_metrics.csv ─────────
# g05_thr edges have no matching bootstrap row; their bootstrap columns are NA.
# This is expected and correct — NA boot columns are a feature, not a defect.

boot_join_cols <- c("spec","wave","trust_stratum","n_cc","edge_a","edge_b")
boot_payload   <- c("sample_weight","boot_mean","boot_sd",
                    "ci_low","ci_high","prop_nonzero","n_boot")

edge_metrics <- edges_all %>%
  left_join(
    boot_edge_metrics %>% select(all_of(c(boot_join_cols, boot_payload))),
    by = boot_join_cols
  ) %>%
  arrange(spec, wave, trust_stratum, desc(abs_weight))

# Report missing-rate by spec (g05_thr should be 100%; g05/g075 should be 0%)
miss_by_spec <- edge_metrics %>%
  group_by(spec) %>%
  summarise(pct_na_boot_mean = mean(is.na(boot_mean)) * 100, .groups = "drop")

cat("Bootstrap NA rate by spec (expected 100% for g05_thr, ~0% for g05/g075):\n")
print(miss_by_spec)

write_csv(edge_metrics, file.path(NETWORK_DIR, "edge_metrics.csv"))
cat("Saved: edge_metrics.csv —", nrow(edge_metrics), "rows\n")
head(edge_metrics, 10)

Bootstrap NA rate by spec (expected 100% for g05_thr, ~0% for g05/g075):

# A tibble: 4 × 2
  spec         pct_na_boot_mean
  <chr>                   <dbl>
1 g05                         0
2 g05_spearman              100
3 g05_thr                   100
4 g075                        0
Saved: edge_metrics.csv — 442 rows

   wave trust_stratum n_cc spec from            to                  weight
1  55   high          309  g05  AFF_FEAR        AFF_WORRY           0.5773954
2  55   high          309  g05  USE2_AVOID      USE2_SPACE150       0.2379412
3  55   high          309  g05  USE2_MASK       USE2_SPACE150       0.2135914
4  55   high          309  g05  USE2_HANDWASH20 USE2_SPACE150       0.2033636
5  55   high          309  g05  AFF_FEAR        SEVERITY            0.1963276
6  55   high          309  g05  USE2_HANDWASH20 USE2_MASK           0.1832615
7  55   high          309  g05  AFF_FEAR        WORRY_HEALTH_SYSTEM 0.1779615
8  55   high          309  g05  USE2_AVOID      USE2_HANDWASH20     0.1445860
9  55   high          309  g05  SEVERITY        USE2_AVOID          0.1407643
10 55   high          309  g05  SEVERITY        USE2_SPACE150       0.1274139
   spec_id  gamma_ebic thresholded ⋯ to_domain from_role    to_role
1  gamma_05 0.5        FALSE       ⋯ affect    non_focal    non_focal
2  gamma_05 0.5        FALSE       ⋯ behavior  non_focal    non_focal
3  gamma_05 0.5        FALSE       ⋯ behavior  non_focal    non_focal
4  gamma_05 0.5        FALSE       ⋯ behavior  non_focal    non_focal
5  gamma_05 0.5        FALSE       ⋯ belief    non_focal    focal_belief
6  gamma_05 0.5        FALSE       ⋯ behavior  non_focal    non_focal
7  gamma_05 0.5        FALSE       ⋯ affect    non_focal    non_focal
8  gamma_05 0.5        FALSE       ⋯ behavior  non_focal    non_focal
9  gamma_05 0.5        FALSE       ⋯ behavior  focal_belief non_focal
10 gamma_05 0.5        FALSE       ⋯ behavior  focal_belief non_focal
   sample_weight boot_mean boot_sd    ci_low     ci_high   prop_nonzero n_boot
1  0.5773954     0.5601251 0.05011639 0.45658259 0.6468484 1.000        1000
2  0.2379412     0.2329179 0.05296988 0.12388081 0.3361304 1.000        1000
3  0.2135914     0.2007787 0.06549991 0.06635812 0.3198839 0.997        1000
4  0.2033636     0.1971649 0.06076647 0.07526566 0.3161542 1.000        1000
5  0.1963276     0.1991228 0.04964673 0.09253927 0.2916246 1.000        1000
6  0.1832615     0.1705988 0.05713821 0.05465144 0.2838080 0.995        1000
7  0.1779615     0.1737192 0.05830889 0.05372568 0.2805723 0.999        1000
8  0.1445860     0.1396358 0.05290904 0.03149183 0.2422949 0.995        1000
9  0.1407643     0.1311757 0.05212756 0.02478151 0.2346041 0.989        1000
10 0.1274139     0.1220673 0.05655952 0.00000000 0.2353568 0.972        1000

## KG-ready metadata tables

`kg_contexts.csv` and `kg_network_instances.csv` are the entity/node tables
loaded into the Belief Knowledge Graph (BKG). Estimation metadata (gamma,
cor_method) is stored as properties on NetworkInstance.

**Scope:** `g05` only — 6 NetworkInstance nodes
(3 waves × 2 trust strata).

**`global_strength`** (sum of absolute edge weights) is computed here and attached
to each NetworkInstance row.

In [15]:
# ── KG-ready metadata tables ──────────────────────────────────────────────────
# Only the main specification (g05) is stored in the BKG.
# GammaSpec is no longer a separate node type; estimation metadata (gamma,
# cor_method) is stored as properties on NetworkInstance.

# global_strength: sum of absolute edge weights per network instance (KG specs only)
gs_per_network <- edges_all %>%
  filter(spec %in% KG_SPECS$spec) %>%
  group_by(network_id) %>%
  summarise(global_strength = sum(abs_weight), .groups = "drop")

kg_network_instances <- edge_metrics %>%
  filter(spec %in% KG_SPECS$spec) %>%
  distinct(spec, wave, trust_stratum, n_cc) %>%
  left_join(KG_SPECS %>% select(spec, spec_id, gamma_ebic, cor_method), by = "spec") %>%
  mutate(
    context_id = paste0("ctx_w", wave, "_", trust_stratum),
    network_id = paste0("net_", spec, "_w", wave, "_", trust_stratum),
    gamma      = gamma_ebic,
    cor_method = cor_method
  ) %>%
  left_join(gs_per_network, by = "network_id") %>%
  arrange(spec, wave, trust_stratum)

kg_contexts <- kg_network_instances %>%
  distinct(context_id, wave, trust_stratum, n_cc) %>%
  mutate(
    trust_variable          = TRUST_VARIABLE,
    trust_grouping_rule     = TRUST_GROUPING_RULE,
    middle_tercile_excluded = MIDDLE_TERCILE_EXCLUDED
  ) %>%
  arrange(wave, trust_stratum)

# ── Assertions ────────────────────────────────────────────────────────────────
n_instances <- nrow(kg_network_instances)
n_contexts  <- nrow(kg_contexts)

# With GammaSpec removed, we expect exactly one instance per context
if (n_instances != n_contexts)
  stop(
    "Expected ", n_contexts, " KG instances (one per context) ",
    "but found ", n_instances, "."
  )

n_gs_na <- sum(is.na(kg_network_instances$global_strength))
if (n_gs_na > 0)
  stop(n_gs_na, " network instance(s) have NA global_strength. ",
       "Check that edges_all covers all KG network_ids.")

cat("KG network instances  :", n_instances, "(one per context)\n")
cat("Contexts              :", n_contexts, "\n")
cat("global_strength range : [",
    round(min(kg_network_instances$global_strength), 4), ",",
    round(max(kg_network_instances$global_strength), 4), "]\n")

write_csv(kg_contexts,            file.path(NETWORK_DIR, "kg_contexts.csv"))
write_csv(kg_network_instances,   file.path(NETWORK_DIR, "kg_network_instances.csv"))

cat("Saved: kg_contexts.csv, kg_network_instances.csv\n")
cat("Note: kg_gamma_specs.csv is no longer exported (GammaSpec removed from BKG schema).\n")
kg_network_instances

KG network instances  : 6 (one per context)
Contexts              : 6
global_strength range : [ 2.3034 , 3.265 ]
Saved: kg_contexts.csv, kg_network_instances.csv
Note: kg_gamma_specs.csv is no longer exported (GammaSpec removed from BKG schema).

  spec wave trust_stratum n_cc spec_id  gamma_ebic cor_method context_id
1 g05  55   high          309  gamma_05 0.5        pearson    ctx_w55_high
2 g05  55   low           376  gamma_05 0.5        pearson    ctx_w55_low
3 g05  56   high          351  gamma_05 0.5        pearson    ctx_w56_high
4 g05  56   low           383  gamma_05 0.5        pearson    ctx_w56_low
5 g05  57   high          407  gamma_05 0.5        pearson    ctx_w57_high
6 g05  57   low           336  gamma_05 0.5        pearson    ctx_w57_low
  network_id       gamma global_strength
1 net_g05_w55_high 0.5   2.948462
2 net_g05_w55_low  0.5   3.177500
3 net_g05_w56_high 0.5   2.655842
4 net_g05_w56_low  0.5   3.048761
5 net_g05_w57_high 0.5   2.303442
6 net_g05_w57_low  0.5   3.265030